name: Generate Snake

on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: TheNaiveSamosa
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push SVG to output branch
        uses: actions/checkout@v2
        with:
          ref: output
        if: success()

      - name: Move SVG to output branch
        run: |
          mkdir -p output
          mv dist/* output/

      - name: Commit & Push to output branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Generated Snake SVG to output branch"
          git push
